### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by AlexanderQueen** [a0rtega/metame#17]
Why i don't have in python script folder, metame script?
Have all requirement installed. Still can't understand how to start dat script.

**Comment by yelingusa** [comment]
Same thing here. After using pip to install, can't use metame from the command prompt. Tried import it in python script but said syntax error.

**Comment by yelingusa** [comment]
I figured out this is how it worked for me. I downloaded the whole package, at cmd promt, types 'python setup.py install', then go into the package build/scriptsx.x/, at the cmd prompt type 'python metame -i myfile.exe -o outfile.exe -d' and it works. myfile.exe is just simply my binary file.

**Comment by AlexanderQueen** [comment]
Thx my nigga bro. Works perfect now.

P.S That moment when random guy solve your problem.
