### ISSUE TITLE
Use r2.cmdj not r2.cmd

### ISSUE THREAD

**Issue by Maijin** [a0rtega/metame#2]
Stop using r2.cmd when using Json command ! Use r2.cmdj

**Comment by a0rtega** [comment]
Oh I didn't know this one. On the other hand, it doesn't make a big difference right? Just returns the parsed json dict.

Using r2.cmd I can choose my own parser (`simplejson` in this case).

**Comment by Maijin** [comment]
it just looks less ugly... `json.loads(self.r2.cmd("ij").replace("\\", "\\\\"))` wtf

**Comment by a0rtega** [comment]
This handles this [bug](https://github.com/radare/radare2/issues/5342) that I reported.

It is fixed in radare2 master now, but there may be people using the release version or previous versions so I kept it.

**Comment by Maijin** [comment]
I would definitely recommend using r2.cmdj, that's all ;P
