### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by moaeddy** [a0rtega/metame#8]
i was stuck at this for hours

[INFO] Opening file with r2

how can i fix it?

**Comment by FFY00** [comment]
Do you have radare2 installed?

**Comment by moaeddy** [comment]
yes, it was installed

**Comment by a0rtega** [comment]
Hello,

This is happening because your binary is probably big, and r2 takes a long time to analyze all the functions.

It's related to r2, so I'll close the issue. Thanks!

**Comment by misterch0c** [comment]
I'm having the same issue and my bin is 14 KiB
